### ISSUE TITLE
[BUG] Crash on player join

### ISSUE THREAD

**Issue by viral32111** [ByMartrixx/player-events#20]
**Describe the bug**
Server crashes due to a `NoSuchMethodError` exception whenever a player joins the server after it has finished starting up.
I'm guessing some method/function was changed between 1.18.1 and 1.18.2, and maybe that caused a mixin to break?

**To Reproduce**
Steps to reproduce the behaviour:
1. Download version 2.2.3 of the mod, along with Fabric loader 0.13.3 and Fabric api 0.47.8, for 1.18.2.
2. Place everything in the `mods` directory.
3. Start the server.
4. Join the server.

**Expected behaviour**
No crash should occur.

**Additional context**
```
java.lang.NoSuchMethodError: 'net.minecraft.class_5414 net.minecraft.class_5349.method_29458()'
        at me.bymartrixx.playerevents.config.PlayerEventsConfig.executeFunctions(PlayerEventsConfig.java:177) ~[player-events-2.2.3.jar:?]
        at me.bymartrixx.playerevents.config.PlayerEventsConfig.doLeaveActions(PlayerEventsConfig.java:290) ~[player-events-2.2.3.jar:?]
        at me.bymartrixx.playerevents.api.event.PlayerLeaveCallback.lambda$static$0(PlayerLeaveCallback.java:11) ~[player_events_api-2.2.3-26cd9d6464dc8938.jar:?]
        at net.minecraft.class_3244.handler$zpf000$onPlayerLeave(class_3244.java:3674) ~[server-intermediary.jar:?]
        at net.minecraft.class_3244.method_10839(class_3244.java:1165) ~[server-intermediary.jar:?]
        at net.minecraft.class_2535.method_10768(class_2535.java:422) ~[server-intermediary.jar:?]
        at net.minecraft.class_1255.method_19537(class_1255.java:88) ~[server-intermediary.jar:?]
        at net.minecraft.class_3244.method_14367(class_3244.java:301) ~[server-intermediary.jar:?]
        at net.minecraft.class_3324.method_14597(class_3324.java:772) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_3782(MinecraftServer.java:608) ~[server-intermediary.jar:?]
        at net.minecraft.class_3176.method_3782(class_3176.java:565) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:729) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:273) ~[server-intermediary.jar:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]
```

**Comment by IotaBread** [comment]
Thanks for reporting this, I'll look into it

**Comment by PortableGames** [comment]
Same problem 😔
