### ISSUE TITLE
[BUG] Claims to support 1.17.1 but errors on launch

### ISSUE THREAD

**Issue by solonovamax** [ByMartrixx/player-events#9]
**Describe the bug**
Cannot run player events on a 1.17.1 server.

**To Reproduce**
Steps to reproduce the behaviour:
1. Install 1.17.1 server
2. Launch server
3. Mixin error stops server startup.

**Expected behaviour**
The mod is listed as supporting 1.17.1 on Modrinth, so it should support 1.17.1

**Additional context**
It's a mixin error. You just need to update the version you're building for.
```
Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Callback method onPlayerJoin(Lnet/minecraft/class_2535;Lnet/minecraft/class_3222;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V in player_events_api.mixins.json:PlayerJoinMixin failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap player-events-api-refmap.json
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:408) ~[server.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1291) ~[server.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1042) ~[server.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:395) ~[server.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:320) ~[server.jar:?]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345) ~[server.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:569) ~[server.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:351) ~[server.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:208) ~[server.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178) ~[server.jar:?]
	at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23) ~[server.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:162) ~[server.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:154) ~[server.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:519) ~[?:?]
	at com.bb1.api.Loader.getRootPath(Loader.java:93) ~[BFAPI-v1-1-7.jar:?]
	at com.bb1.api.config.Config.<clinit>(Config.java:52) ~[BFAPI-v1-1-7.jar:?]
	at com.bb1.api.Loader.<clinit>(Loader.java:104) ~[BFAPI-v1-1-7.jar:?]
	at java.lang.Class.forName0(Native Method) ~[?:?]
	at java.lang.Class.forName(Class.java:466) ~[?:?]
	at net.fabricmc.loader.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:50) ~[server.jar:?]
	at net.fabricmc.loader.EntrypointStorage$NewEntry.lambda$getOrCreate$0(EntrypointStorage.java:106) ~[server.jar:?]
	at java.util.HashMap.computeIfAbsent(HashMap.java:1224) ~[?:?]
	at net.fabricmc.loader.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:104) ~[server.jar:?]
	at net.fabricmc.loader.EntrypointStorage.lambda$getEntrypointContainers$1(EntrypointStorage.java:191) ~[server.jar:?]
	at net.fabricmc.loader.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:37) ~[server.jar:?]
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[server.jar:?]
	... 17 more
```

**Comment by solonovamax** [comment]
Sorry, this is an issue with Fabric Death Messages which uses your API.

I wrongly assumed this to be the cause of it.

**Comment by IotaBread** [comment]
No worries
